server:
  port: 16015

spring:
  datasource:
    url: ENC(Z+vE1oXlOGMjyrqnWGi9+DzjxN4o7VFuAjQfcRWVFv1hKgZhJamTbxOY1QBm9qOYxIi7Pt2qvA1oQ0qg7QKlglXZz9hluiqhGjtQXmnPk9FSVX7N0YhNuIXY5pKaua2bipseHohGObYojk3ipWHTHQ==)
    driver-class-name: ENC(ONsngNq34YN+R+cWDYBwq2fHcZNCBhwM+U8mV8re6LmFiWraebf4rXZSGmjylj2GnzZOhSYtlNBj0rr8Xs5DpA==)
    username: ENC(w9ssAtRYjmMUDjBXkqo7tw69wYL5YVFNsa17otsO6SIJ7Wj+6TwxsEamB4WmZkLl)
    password: ENC(bfpMfCTQ6ogXirAvCp/bNvxy2uGg51/EBT6oGTUL0eEdNGuGjSCGs+m4BIUvN1yhDe0Hn5BouhkU4Z36Wj36Nw==)
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      database-platform: ENC(/lFeSZf4jrfhQMibteFiF1zHJdsz6ALnuzBuQN5/BmTpY2LOQ9abzEKBV8kiYm5zMZjJ3vcQIEPxT3e8KtMt2ALhEe/4zmdQS/VHL0Ba+UM=)

jenkins:
  user: ENC(rKaCixWBS/Q+EWwEK/Ni0B7yEIfA9MfYBCbpIPpZrBKT/mAr4MFoUgjpAFIB9Qtx)
  token: ENC(QFs/crXcjrxBM6PMBKWiYSLeyaANt8AhIFJ7X3nLU4e9hDhwL3OAYDlfTCIlSutN5wYTgE7aLcHPvA9YYURavMwy3B0AK/FG95cVQmvYA1g=)
  endpoint: ENC(DPi7pIwGAC5LTpubGRGBmoARU1Fp5ZZ9/XjaTKdKyPA5ewIfVhl3IngvK0sp8z6Tb8SuLumYiy4zcm7cF50x0oB4ztYLNSzliom9TtZCd7c=)
  testapi: ENC(DYpKCJGUyw3ifE1WqEi7PIAN8E2950hqVAQmbYRkFV9NChP2GNtwzNo1SZk32XuN9CdeW7kaKoNWCnSdXAaH9VVNFvusIkMvx2pYcq/6q1I=)

endpoint:
  jenkins_api: http://127.0.0.1:8000/

api:
  jenkins:
    job:
      trigger: /job/trigger

logging:
  level:
    com:
      srm:
        projectmanager: debug
